### ISSUE TITLE
arrow problem (umlet hangs forever when dragging end to end)

### ISSUE THREAD

**Issue by amin-amani** [umlet/umlet#523] opened 2018-11-04 15:57 UTC
Hi 
there is a problem with dashed arrow element.when i want to resize a dashed arrow element suddenly array start point and endpoint located on each other application crashed.

**Comment by afdia** [comment] 2018-11-18 10:14
sorry I don't understand the problem description. What do you mean with "resizing arrows"? Dragging new points from the relation line or moving a relation end around? And what do you mean with "each other application crashed"?

In general the behavior of a relation is always the same, so it shouldn't depend on the arrow style (dashed vs solid).

**Comment by amin-amani** [comment] 2018-11-25 21:30
fillow these steps:
1.in activity diagram double click on array to bring array element on stage.
2.click on array to select that.
3.drag end of array and move  mouse toward tip of array

**Comment by afdia** [comment] 2018-11-26 19:35
I cannot reproduce it, maybe it's the same issue as #349
Can you try another JDK? Which Umlet version are you using?

**Comment by amin-amani** [comment] 2018-11-28 13:10
thank you
yes it seems  same problem .it happen when i want to drag end of array and move mouse toward tip of array . my umlet version is 14.3.0 

amin@amin-pc:~$ java -version
![screenshot from 2018-11-28 16-27-54](https://user-images.githubusercontent.com/25980318/49153705-b6c04f80-f32b-11e8-8fbf-9b5e819af071.png)

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
amin@amin-pc:~$ uname -a
Linux amin-pc 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by afdia** [comment] 2023-10-11 18:10
If it happens again with Java11+ please reopen, otherwise I will close it as we cannot do anything about it and Java8 is quite old

**Closed by afdia** 2023-10-11 18:10 UTC
Labels: duplicate, bug, relation, jdk issue
