### ISSUE TITLE
Default font settings not saved (OSX, 14.1.1)

### ISSUE THREAD

**Issue by paulrahme** [umlet/umlet#369] opened 2016-03-15 00:43 UTC
When going into File -> Options and changing "Default fontsize" and "Default fontfamily", it resets to the original values next time Umlet is opened.

Using Umlet 14.1.1 on OSX 10.11.3, and logged in as an Admin user.

**Comment by afdia** [comment] 2016-03-16 07:19
Please make sure that the file ~/Library/Preferences/UMLet/umlet.cfg is writable

It should store the default fontsize and familty as the following values:
default_fontsize=14
default_fontfamily=SansSerif

**Comment by paulrahme** [comment] 2016-03-17 00:14
The folder was empty, so I created umlet.cfg, added those 2 lines, and did a 'chmod 666' on it just to be sure.

Changing the font settings in File->Options, then quitting and restarting UMLet still doesn't keep the settings.

However I've noticed that if I change the contents of that file manually, UMLet seems to read them in ok.

Anything I can do to help check why it's not updating that file from inside the app?

**Comment by afdia** [comment] 2016-03-17 06:15
Perhaps you can start UMLet from the shell, change the setting and stop it.
Afterwards you can check if a stacktrace is printed to the console. If an error happens right before the configuration is stored, it should be printed.

Other than that perhaps try to close UMLet using the menu (File > Exit) instead of the red "close button"

**Comment by paulrahme** [comment] 2016-03-17 06:33
Ah, that last bit helped me found what it is.

On mac, it runs through Java so the main menubar (at the top of the screen) has a single menu called "MainStandAlone", so pressing the usual Command-Q to quit closes the Java wrapper, bypassing File -> Exit.

Using File -> Exit inside the UMLet window saves the .cfg file as expected.

Perhaps it can save the settings when the Options window is closed instead, unless it's possible to hook into the parent Java 'quit' event...?

**Comment by afdia** [comment] 2016-03-17 07:27
Good to hear that there is at least this workaround.

Currently the config is saved explicitly when File > Exit is called and also when the main windows is closed (by using a Swing windows listener).

Saving when options are closed would not work because some properties are not set through the options window (e.g. the recent file list)

After some search, I have found that there is an alternative way to do something when the application is closed as described in http://stackoverflow.com/a/2361567
It uses "Runtime.getRuntime().addShutdownHook" which could probably also trigger in your case

After further searching I have found other people with the same problem: https://stackoverflow.com/questions/2061194/swing-on-osx-how-to-trap-command-q/2061318

Perhaps you can start Umlet from the commandline with the following command:
`java -Dapple.eawt.quitStrategy=CLOSE_ALL_WINDOWS -jar umlet.jar`
and see if that fixes the problem.

**Comment by paulrahme** [comment] 2016-03-18 01:54
Yes, running that from the command line saves the Options correctly on quit, even when I use Command-Q to quit the 'MainStandAlone' java VM.

**Comment by afdia** [comment] 2016-03-18 06:51
perfect, that means it should also work if I set the property directly after startup.

The problem is fixed and next release should save the settings as expected.

**Closed** 2016-03-18 06:52 UTC
Labels: bug, mac os x

**Comment by paulrahme** [comment] 2016-03-20 23:30
Great stuff, thanks and looking forward to the next release!
