### ISSUE TITLE
Umlet 14.2 menu items can't be clicked in Ubuntu 14.04

### ISSUE THREAD

**Issue by cvetan** [umlet/umlet#376] opened 2016-04-23 15:37 UTC
I have problems with the UMLet in Ubuntu.

Latest version that i could use without problems is 12.x.

When i run Umlet, and monitor terminal activity, it throws Exception related to AWT, when menu is clicked.

Just to mention, i turn off global menu for Umlet, so that shouldn't be the issue.

Here is the terminal output:
`2016-04-23 17:35:49,274 |      0 | INFO  | com.baselet.control.enums.Program | Initializing Program: Version=14.2, Runtime=STANDALONE
2016-04-23 17:35:49,368 |     94 | INFO  | com.baselet.control.Main       | Initializing GUI ...
2016-04-23 17:35:51,360 |   2086 | INFO  | com.baselet.control.Main       | GUI initialized
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at javax.swing.JEditorPane.registerEditorKitForContentType(JEditorPane.java:1247)
	at javax.swing.JEditorPane.registerEditorKitForContentType(JEditorPane.java:1229)
	at javax.swing.JEditorPane.loadDefaultKitsIfNecessary(JEditorPane.java:1307)
	at javax.swing.JEditorPane.getKitTypeRegistry(JEditorPane.java:1264)
	at javax.swing.JEditorPane.createEditorKitForContentType(JEditorPane.java:1189)
	at javax.swing.JEditorPane.getEditorKitForContentType(JEditorPane.java:1088)
	at javax.swing.JEditorPane.setContentType(JEditorPane.java:979)
	at javax.swing.JEditorPane.handleConnectionProperties(JEditorPane.java:783)
	at javax.swing.JEditorPane.getStream(JEditorPane.java:757)
	at javax.swing.JEditorPane.setPage(JEditorPane.java:435)
	at com.baselet.diagram.StartUpHelpText.showHTML(StartUpHelpText.java:93)
	at com.baselet.diagram.StartUpHelpText.<init>(StartUpHelpText.java:57)
	at com.baselet.diagram.DrawPanel.<init>(DrawPanel.java:96)
	at com.baselet.diagram.DiagramHandler.createDrawPanel(DiagramHandler.java:93)
	at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:71)
	at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:64)
	at com.baselet.control.Main.doNewHelper(Main.java:95)
	at com.baselet.control.Main.access$100(Main.java:34)
	at com.baselet.control.Main$2.run(Main.java:86)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.baselet.gui.menu.MenuFactory$1.run(MenuFactory.java:83)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.baselet.gui.menu.MenuFactory$1.run(MenuFactory.java:83)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by cvetan** [comment] 2016-04-23 15:44
It is related to jayatana. It breaks when i have jayatana package installed. 

Can i somehow disable jayatana only for Umlet. I know that previouse version of PhpStorm, had it disabled. So i used it normally with Netbeans for instance.

**Comment by cvetan** [comment] 2016-04-23 16:14
OK. I've disabled it in sh script.

But it would be nice if jayatana could be integrated as for other applications. :)

**Comment by afdia** [comment] 2016-04-23 20:06
This is a known issue (see #312) which is probably caused by the library we use for the properties panel, therefore I don't think that we can do anything to fix that at the moment.

**Comment by cvetan** [comment] 2016-04-23 20:52
Yes i know. I unset environmental variable for the Umlet. It works. :) That is most important.

**Comment by afdia** [comment] 2016-05-12 12:16
I hope we will find a better way to fix this in the future. I close this as a duplicate of #312

**Closed by afdia** 2016-05-12 12:16 UTC
Labels: bug, duplicate
