### ISSUE TITLE
New in version 13.3 hung with eclipse on mac

### ISSUE THREAD

**Issue by titushoe** [umlet/umlet#307] opened 2015-08-27 14:12 UTC
The new umlet-version 13.3 hung up with eclipse on mac:
Eclipse IDE for Java Developers
Version: Mars Release (4.5.0)
Build id: 20150621-1200

![bildschirmfoto 2015-08-27 um 16 09 31](https://cloud.githubusercontent.com/assets/13999380/9522642/1235f37e-4cd6-11e5-88b4-81adc46c9551.png)

But the version 13.2 works fine !!

If you need more informations please contact me !!

**Comment by afdia** [comment] 2015-08-28 08:23
What do you mean with "hung up"? Eclipse hangs after opening an umlet diagram?

Can you please check the content of the eclipse_workspace/.metadata/.log file for any errors?
Also please check the "Error Log" view if there are any umlet related errors

**Comment by titushoe** [comment] 2015-08-28 12:02
Hello afdia,

here for you the contents of my .metadata from workspace as compressed tar-file - but its renamed to gif-ending to attach them
If i could more do for you let me know !!
UMLet is a very good tool!!
![eclipse_meta tz](https://cloud.githubusercontent.com/assets/13999380/9545778/2d060894-4d8d-11e5-90c4-e82729c7b04a.gif)

**Comment by afdia** [comment] 2015-08-28 12:14
Hi

There is indeed an error in the log file:

!MESSAGE Invalid input url:platform:/plugin/com.umlet.plugin/img/umlet_eclipse.gif
!STACK 0
java.io.IOException: Unable to resolve plug-in "platform:/plugin/com.umlet.plugin/img/umlet_eclipse.gif".
	at org.eclipse.core.internal.runtime.PlatformURLPluginConnection.parse(PlatformURLPluginConnection.java:65)
	at org.eclipse.core.internal.runtime.FindSupport.find(FindSupport.java:290)
	at org.eclipse.core.runtime.FileLocator.find(FileLocator.java:152)
	at org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:215)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:283)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:224)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:202)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImageFromURI(SWTPartRenderer.java:225)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImage(SWTPartRenderer.java:236)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.createTab(StackRenderer.java:877)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.processContents(LazyStackRenderer.java:139)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:654)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:654)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:525)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:509)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:69)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:654)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:654)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveRenderer.processContents(PerspectiveRenderer.java:49)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:654)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.showTab(PerspectiveStackRenderer.java:82)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:103)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.postProcess(PerspectiveStackRenderer.java:63)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:654)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.processContents(WBWRenderer.java:614)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:654)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1061)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)


Unfortunately it's not enough to find the underlying problem, therefore please try the following:
1. start "eclipse -clean" the clean argument forces eclipse to refresh some plugin caches
2. use a new workspace because some of the info which can be found for this error (for any kind of plugin; see https://www.google.at/search?output=search&sclient=psy-ab&q=at+org.eclipse.core.internal.runtime.PlatformURLPluginConnection.parse%28PlatformURLPluginConnection.java:65%29&btnG=&oq=&gs_l=&pbx=1&gws_rd=cr&ei=mU_gVdbGM8H0UtTzqNgD) suggests that this can be caused by an old workspace

If those 2 things don't help please describe what you mean with "hung up". Perhaps this will help.

Thanks
1. use a new workspace location

**Comment by titushoe** [comment] 2015-08-30 15:40
Hi afdia,

so i have now a little time to make the tests that you proposed.
I have now started eclipse wit -clean:
DieterSfertsMBP:~ titus$ /Applications/Eclipse.app/Contents/MacOS/eclipse -clean &
[1] 28530
DieterSfertsMBP:~ titus$ org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.

and than i have switched to a new workspace !!

now what all "hung up"

the first thing is i could not edit in properties:
![bildschirmfoto 2015-08-30 um 16 32 47](https://cloud.githubusercontent.com/assets/13999380/9567955/542cfe7c-4f3c-11e5-8a74-fd4d0da6b50c.png)

The next thing is if i try to save or reopen the .uxf-file the eclipse hung up with an sand glass and i must kill to stop them and the will ist sen an error- message to Apple!!

Here now the tar of the new workspace:
![umlet_test tgz](https://cloud.githubusercontent.com/assets/13999380/9567980/a6820f22-4f3d-11e5-86bc-c9b3bb3d32f2.jpg)

It should include all err-massage's in files.

On the terminal i have seen the following output:
DieterSfertsMBP:~ titus$ /Applications/Eclipse.app/Contents/MacOS/eclipse -clean &
[1] 28530
DieterSfertsMBP:~ titus$ org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /Users/titus/Ework/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.6.0.20150526-2032.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://659.fwk1047503754:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://659.fwk1047503754:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
java.lang.VerifyError: Illegal type at constant pool entry 47 in class com.yattasolutions.umllab.validation.a$b
Exception Details:
  Location:
    com/yattasolutions/umllab/validation/a$b.a(Lorg/objectweb/asm/ClassWriter;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V @112: invokeinterface
  Reason:
    Constant pool index 47 is invalid
  Bytecode:
    0x0000000: 1906 b800 383a 0902 360a 1909 be04 6436
    0x0000010: 0ba7 0021 1909 150b 32b6 0039 3a0c 1205
    0x0000020: 190c b600 2599 000a 150b 360a a700 0b84
    0x0000030: 0bff 150b 9cff e015 0a02 a000 21bb 000c
    0x0000040: 59bb 000f 5912 04b7 0029 1905 b600 2a19
    0x0000050: 06b6 002a b600 2bb7 0023 bf2b 1504 1010
    0x0000060: 6019 0519 0619 0719 08b6 002d 3a0b 190b
    0x0000070: b900 2f01 0019 0b10 1903 b900 3703 0019
    0x0000080: 0b19 05b9 0034 0200 190b 1019 0415 0a60
    0x0000090: b900 3703 0019 0b11 00b6 2c12 0612 02b9
    0x00000a0: 0036 0500 bb00 1359 b700 2e3a 0c19 0b11
    0x00000b0: 009a 190c b900 3203 0019 0b07 b900 3102
    0x00000c0: 0019 0b11 00ac b900 3102 0019 0b19 0cb9
    0x00000d0: 0033 0200 0336 0da7 004d 150d 9a00 0810
    0x00000e0: 0aa7 000d 1909 150d 0464 32b6 003a 360e
    0x00000f0: 150e aa00 0000 0024 0000 0009 0000 000a
    0x0000100: 0000 0016 0000 0016 190b 1019 150d b900
    0x0000110: 3703 00a7 000e 190b 1015 150d b900 3703
    0x0000120: 0084 0d01 150d 1909 bea4 ffb1 190b 1100
    0x0000130: b72d 1905 1906 b900 3605 0019 0b11 00ac
    0x0000140: b900 3102 0019 0b03 03b9 0035 0300 190b
    0x0000150: b900 3001 00b1                         
  Stackmap Table:
    full_frame(@20,{Top,Object[#18],Object[#14],Object[#14],Integer,Object[#14],Object[#14],Object[#14],Object[#7],Object[#8],Integer,Integer},{})
    same_frame(@47)
    same_frame(@50)
    chop_frame(@55,1)
    same_frame(@91)
    full_frame(@218,{Top,Top,Top,Object[#14],Top,Object[#14],Object[#14],Top,Top,Object[#8],Top,Object[#20],Top,Integer},{})
    same_frame(@228)
    same_locals_1_stack_item_frame(@238,Integer)
    same_frame(@264)
    same_frame(@278)
    same_frame(@289)
    same_frame(@292)

	at com.yattasolutions.umllab.validation.a.a(SourceFile:206)
	at com.yattasolutions.umllab.validation.a.S(SourceFile:149)
	at com.yattasolutions.umllab.validation.a$1.adA(SourceFile:101)
	at com.yattasolutions.umllab.validation.a$1.findClass(SourceFile:91)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.yattasolutions.umllab.validation.a.R(SourceFile:119)
	at com.yattasolutions.umllab.validation.f.<clinit>(SourceFile:40)
	at com.yattasolutions.obf.os.a.earlyStartup(SourceFile:17)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:90)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:68)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$56.run(Workbench.java:2812)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

DieterSfertsMBP:~ titus$ 
DieterSfertsMBP:~ titus$ 
DieterSfertsMBP:~ titus$ org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
org.eclipse.m2e.logback.configuration: Logback config file: /Users/titus/umlet_test/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.6.0.20150526-2032.xml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://659.fwk1047503754:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://659.fwk1047503754:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
org.eclipse.m2e.logback.configuration: Initializing logback
java.lang.VerifyError: Illegal type at constant pool entry 47 in class com.yattasolutions.umllab.validation.a$b
Exception Details:
  Location:
    com/yattasolutions/umllab/validation/a$b.a(Lorg/objectweb/asm/ClassWriter;Ljava/lang/String;Ljava/lang/String;)V @15: invokeinterface
  Reason:
    Constant pool index 47 is invalid
  Bytecode:
    0x0000000: 2b04 1203 1201 0101 b600 2d3a 0419 04b9
    0x0000010: 002f 0100 1904 1019 03b9 0037 0300 1904
    0x0000020: 1100 b72d 1203 1201 b900 3605 0019 0411
    0x0000030: 00b1 b900 3102 0019 0404 04b9 0035 0300
    0x0000040: 1904 b900 3001 00b1                    

	at com.yattasolutions.umllab.validation.a.a(SourceFile:206)
	at com.yattasolutions.umllab.validation.a.S(SourceFile:149)
	at com.yattasolutions.umllab.validation.a$1.adA(SourceFile:101)
	at com.yattasolutions.umllab.validation.a$1.findClass(SourceFile:91)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.yattasolutions.umllab.validation.a.R(SourceFile:119)
	at com.yattasolutions.umllab.validation.f.<clinit>(SourceFile:40)
	at com.yattasolutions.obf.os.a.earlyStartup(SourceFile:17)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:90)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:68)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$56.run(Workbench.java:2812)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.baselet.gui.listener.PropertyPanelListener.updateGridElement(PropertyPanelListener.java:43)
	at com.baselet.gui.listener.PropertyPanelListener$1.run(PropertyPanelListener.java:36)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.baselet.gui.listener.PropertyPanelListener.updateGridElement(PropertyPanelListener.java:43)
	at com.baselet.gui.listener.PropertyPanelListener$1.run(PropertyPanelListener.java:36)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000121dc9ce9, pid=29840, tid=24579
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libswt-cocoa-4527.jnilib+0x25ce9]  callback+0x297
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Applications/Eclipse.app/Contents/MacOS/hs_err_pid29840.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

[1]+  Done                    /Applications/Eclipse.app/Contents/MacOS/eclipse -clean

Best regards 
titus

**Comment by afdia** [comment] 2015-08-30 18:07
Thanks for the additional info

Unforunately we don't have a developer with a mac at the moment who could reproduce such bugs (there are some eclipse osx bugs in the issue tracker)

The weird thing is that you say that v13.2 does work but 13.3 doesn't. There are no eclipse specific changes and  the one umlet specific error in the log:

**Comment by afdia** [comment] 2018-08-27 17:54
I'm closing this issue in favor of #399 which describes the same problem and offers a workaround

**Closed by afdia** 2018-08-27 17:54 UTC
Labels: bug, eclipse plugin, help wanted, mac os x
