### ISSUE TITLE
Word wrap in edit window.

### ISSUE THREAD

**Issue by kv-gits** [umlet/umlet#454] opened 2017-05-06 06:55 UTC
Umlet is best. But one thing I cant handle without frustrating. It is possible to make word wrap inside block. But how to make word wrap inside edit window? Sure, it is very simple but why missed?

**Comment by afdia** [comment] 2017-05-11 06:45
I've tried to implement it, but there are some issues which block the feature for the moment
I'm closing this issue as a duplicate of #429

**Closed by afdia** 2017-05-11 06:45 UTC
