### ISSUE TITLE
request to add dark theme

### ISSUE THREAD

**Issue by gongjun116403737** [umlet/umlet#633] opened 2021-03-25 02:16 UTC
as title.

**Comment by javgat** [comment] 2021-03-27 14:48
duplicate of #566

**Closed** 2021-03-29 07:23 UTC

**Comment by gongjun116403737** [comment] 2021-03-29 07:26
> duplicate of #566

Is there any dark theme solution provided ?

**Comment by javgat** [comment] 2021-03-29 10:31
Not really, someone said to use "xcalib -i -a" but i don't really like that.

They said that:
> It's an interesting idea, but maybe not that easy with Umlet's draw panel which is mostly white (and we cannot really change that because diagram elements may be explicitly colored and visibility would be impaired if e.g. a blue foreground is on a gray or black diagram background)

But I think that having some optional dark theme available that only work for some people's diagrams is better than not having any solution.

The issue is still open, that's why i linked it.
