### ISSUE TITLE
Exported image with high resolution (support retina display)

### ISSUE THREAD

**Issue by ppggff** [umlet/umlet#510] opened 2018-07-18 08:28 UTC
version: 14.2
The exported image looks blurred on macbook with a retina display.

**Comment by PapsOu** [comment] 2018-07-31 14:03
You should export it as SVG

**Comment by afdia** [comment] 2018-07-31 18:46
I'm not sure what you mean with "blurred", perhaps you can upload an example and let me know which export format you have chosen.

I suggest to use SVG or PDF which typically look the best on any resolution, because they are vector based formats

**Comment by ppggff** [comment] 2018-08-01 02:14
Thanks.

I know SVG will looks better, but sometime PNG or other format are useful.
I hope the exported image is as clear as the screenshot.

There is the example:
 * the PNG file
   ![t](https://user-images.githubusercontent.com/2892417/43497101-2b039ea4-9573-11e8-8539-75c9f7399cbb.png)

 * the screenshot of same diagram in umlet editor
   <img width="366" alt="screen shot 2018-08-01 at 10 07 59" src="https://user-images.githubusercontent.com/2892417/43497115-36594588-9573-11e8-9269-af0dbeb17f96.png">

**Comment by afdia** [comment] 2018-08-01 05:47
Thanks for the samples.
It's weird because for me the exported PNG looks sharper, because for example the actor it is exactly 1px width. On the screenshot there is a "shadow" of the line which may look like a blur.

Here is a screenshot how it looks if I zoom in 2x (I hope the "shadow" is now visible):
![comp](https://user-images.githubusercontent.com/8770707/43503211-99b293a6-955e-11e8-965b-a981c0122a43.png)

**Comment by ppggff** [comment] 2018-08-01 09:35
Here is the screenshot if I zoom in 2x:

<img width="522" alt="screen shot 2018-08-01 at 17 25 58" src="https://user-images.githubusercontent.com/2892417/43513341-1a3a94f0-95b0-11e8-8ced-de0f2ddc8a62.png">

The different comes from how apple's retina work, this link maybe help to explain it. https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/

The resolution and scale of these image are:

|img|size|DPI|scale factor|
|-|-|-|-|
|exported png|270x280|72 pixels/inch|1x|
|screenshot|732x574|144 pixels/inch|2x|

Since the editor area of Umlet is able to display high resolution image, maybe there is a
way to generate high resolution exported image too.

**Comment by afdia** [comment] 2018-08-02 07:48
Thanks for the details, I'm not sure if there is an easy way to fix the problem, but perhaps someone with a retina display can try to fix this.

In the meantime, my suggested workaround would be using vector based export formats like SVG or PDF and if needed transform those to images (I guess there are several programs to do this)

**Comment by ppggff** [comment] 2018-08-29 16:51
I create a prototype to export PNG for retina in pull request, please check it.
#514

**Comment by ppggff** [comment] 2020-09-14 06:44
Hi, @afdia , may I ask if this problem has been solved?

**Comment by afdia** [comment] 2020-09-15 19:44
Hi, as you might know we're currently developing the umlet vscode plugin and it already offers a scaling option for the PNG export (which is basically a size multiplier):
![grafik](https://user-images.githubusercontent.com/8770707/93256637-e4de8000-f79b-11ea-9eab-9cb38ac0ff2e.png)

Unfortunately it is not ported to the classic standalone umlet at the moment, but I would suggest to implement it in a similar style. If you want to update your pull request to offer a similar style of configuration option for standalone umlet (instead of a separate new export option with another fixed multiplier) I would be happy to accept it, otherwise I can talk to the guys who are developing the vscode plugin if they want to add it to standalone too (your existing pull request already shows how the scaling can be implemented)

I guess we will make a release for all umlet platforms soon after we gathered enough feedback for the new plugin, so this could be part of the next release

**Comment by ppggff** [comment] 2020-09-16 02:52
I tried the new vscode plugin, the new scaling option currently only changes the size of the exported file, but it does not change the DPI of the file, so it does not address this issue. I will try to update my PR to match the 'configuration option' style.

And when drawing in vscode, I notices that the diagram in drawing area is also lack for DPI:
<img width="409" alt="Screenshot 2020-09-16 at 10 47 25 AM" src="https://user-images.githubusercontent.com/2892417/93286517-05ddba00-f80a-11ea-83ee-61c13b69e36d.png">
(compare the text between them) 
I was under the impression that standalone mode didn't have this problem, hopefully this will be fixed soon.

**Comment by afdia** [comment] 2020-09-16 05:18
Thanks for trying the vscode plugin, as it's based on the javascript version of Umlet (www.umletino.com) it draws on an HTML canvas which probably doesnt support high DPI without further changes. Maybe https://www.html5rocks.com/en/tutorials/canvas/hidpi/ will help us solving the issue

About the export: I'm currently implementing it via options/config and will let you know when you can try it out

**Comment by afdia** [comment] 2020-09-16 06:13
I have tried to fix the issue on the branch https://github.com/umlet/umlet/tree/510_dpi
There are 2 changes:

1. There is a new option to scale exported images which is persisted in the umlet config (your old retina export has scale 2, so you should get the same results if you set it to 2)
2. I try to set the correct DPI before exporting. If it fails it just uses the old img export method. It seems that only BMP export fails, the others work

Please check out the branch, try it out and let me know if it works. If everything is ok I will merge it afterwards.
(Without having a high DPI monitor the whole DPI setup code does basically nothing for me (only the scaling factor makes a difference) so I'm not able to test if it really works)

The fix for the html canvas (for umletino and vscode plugin) is more complicated so I'm not sure if we are able to fix it soon.

-----

Just as a note for umlet-gwt devs: The umlet-gwt class DrawCanvas.java which instantiates the canvas has to apply some function calls to fix the DPI which unfortunately breaks the drag&drop logic (elements move too slow afterwards)
The easiest way to apply canvas modifications in GWT while still using the GWT Canvas object is something like this (based on https://stackoverflow.com/questions/14488849/higher-dpi-graphics-with-html5-canvas/26047748#26047748 ):
```
	public static native Canvas setupCanvas(Element canvas, int dpi) /*-{
		//@formatter:off
    // Set up CSS size.
    canvas.style.width = canvas.style.width || canvas.width + 'px';
    canvas.style.height = canvas.style.height || canvas.height + 'px';

    // Resize canvas and scale future draws.
    var scaleFactor = dpi / 96;
    canvas.width = Math.ceil(canvas.width * scaleFactor);
    canvas.height = Math.ceil(canvas.height * scaleFactor);
    var ctx = canvas.getContext('2d');
    ctx.scale(scaleFactor, scaleFactor);
		//@formatter:on
	}-*/;
	public DrawCanvas() {
		setupCanvas(canvas.getElement(), 96); // fix canvas DPI after instantiation
	}
```
Al alternative would be switching to GWT elemental 2 and use its HTMLCanvasElement which probably offers all required methods and will also work with GWT 3 (but we already use some native calls so I'm not sure if its worth it). If not the methods can be extended with JSInterop

**Comment by ppggff** [comment] 2020-09-17 04:10
I tried this new branch.

When scaling is set to 2, the exported png file is the desired size and DPI(144). 
when scaling is set to 1, the png file still has a DPI of 144, and the result is that the image looks much smaller.
<img width="732" alt="Screenshot 2020-09-17 at 12 06 39 PM" src="https://user-images.githubusercontent.com/2892417/93419015-4149b880-f8de-11ea-9849-7a5f295c1347.png">
(left: scaling==2,  right: scaling==1)

Other types of files (bmp, jpeg) change size according to scaling settings, but the DPI remains the same, at 72.

Should we use different options for scaling and DPI?

**Comment by afdia** [comment] 2020-09-17 07:02
Thanks for testing!

I compared the export from master-umlet and the branch (both with scaling factor of 1)
The png from master-umlet doesnt store a dpi value in its properties and shows a print size of "10.58 x 19.75 cm, 4.17 x 7.78 inches"
The png from the branch stores the dpi value of "144x144" and shows a print sizeh of nd it shows the "printing size" as "5.29 x 9.88 cm, 2.08 x 3.89 inches" (therefore if scaling x2 is set it will result in the same cm/inch size but at a higher dpi value)

To sum things up:
* Scaling changes the amount of pixels used for the image and works for all image-types
* the dpi value (which is written by the "dpi related code") is only supported by png because its basically just metadata which is stored within the image format (which has to support such metadata)
* the dpi value is only read and used by high-dpi "retina" displays. At least my non-retina monitor on windows ignores the value.

Therefore I thing a good way to solve the issue is:
* leave the scaling factor in the options but unlink it from dpi modifications
* by default no dpi information is stored within images, but I will add an optional config entry to set the dpi property (but I think it should not be part of the GUI options panel because its just too specific and we try to keep the options at least somewhat simple)

What do you think?
Btw: I've never worked on a high-dpi monitor, but how do other programs or websites handle this problem? I guess most images you will see on the web or from cameras, other programs, ... don't store dpi values (most images are probably jpegs so it's not even possible).
How do they handle this issue if scaling to double the amount of pixels alone is not enough?

**Comment by ppggff** [comment] 2020-09-18 02:24
> Therefore I thing a good way to solve the issue is:
> 
> * leave the scaling factor in the options but unlink it from dpi modifications
> * by default no dpi information is stored within images, but I will add an optional config entry to set the dpi property (but I think it should not be part of the GUI options panel because its just too specific and we try to keep the options at least somewhat simple)

That's good.
So how do you set the dpi?

> What do you think?
> Btw: I've never worked on a high-dpi monitor, but how do other programs or websites handle this problem? I guess most images you will see on the web or from cameras, other programs, ... don't store dpi values (most images are probably jpegs so it's not even possible).
> How do they handle this issue if scaling to double the amount of pixels alone is not enough?

I tried draw.io, it supports to set DPI in advanced export (writeGraphModelToPng?).

**Comment by afdia** [comment] 2020-09-18 05:05
There are 2 new configurations:
* export_scale: also available in the options, default is 1
* export_dpi: not visible in the options, default ist null (therefore no dpi value is stored)

If you set export_scale=2 and export_dpi=144 you should get the result you're expecting.

I have tried it and it seems to work, but please try it out to confirm there are no issues before I merge the change into master.
It's on the https://github.com/umlet/umlet/tree/510_dpi

**Comment by ppggff** [comment] 2020-09-18 06:41
It works, thanks a lot

**Comment by afdia** [comment] 2020-09-19 06:25
ok thanks, it will be part of the next release

**Closed by afdia** 2020-09-19 06:25 UTC
Labels: bug, help wanted, mac os x
