### ISSUE TITLE
NullPointerException for diagrams with help_text in Batch Mode

### ISSUE THREAD

**Issue by pdudits** [umlet/umlet#244] opened 2015-03-18 10:09 UTC
Following exception is reported when running UMLet 13 in batch mode:

````
java.lang.NullPointerException
        at com.baselet.diagram.io.InputHandler.endElement(InputHandler.java:83)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1789)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2965)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
        at com.baselet.diagram.io.DiagramFileHandler.doOpen(DiagramFileHandler.java:251)
        at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:74)
        at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:58)
        at com.baselet.control.Main.doConvert(Main.java:218)
        at com.baselet.control.Main.main(Main.java:121)
````

SInce batch has no GUI, a null check is needed in InputHandler or a headless gui implementation.

**Comment by pdudits** [comment] 2015-03-18 10:09
Are you ready to accept pull requests now that migration is finished? I could handle the first approach.

**Comment by afdia** [comment] 2015-03-19 06:01
Thanks for the report.
Yes in general we do accept pull requests now (although only if you donate the code to us with free use because we typically do not mention authors throughout the codebase to keep it clean)

One more question though: which version of umlet are you using? I cannot reproduce the issue (not in normal and not in headless mode) in v13.2 on Windows7 using JDK 1.8.0_31, so perhaps it's already fixed?

The command I tried was:
java -jar umlet.jar -action=convert -format=jpg "-filename=D:/UML Class.uxf" -output=D:\output.jpg -Djava.awt.headless=true

**Comment by pdudits** [comment] 2015-03-19 09:36
It was also 13.2 on JDK 1.7.0_45, but the source files were created with 11.5.1.

The issue is with the help_text element, I've put a minimal testcase [over here](https://gist.github.com/pdudits/68134a6727829a078956)

**Comment by afdia** [comment] 2015-03-19 14:53
ah ok thanks for the testcase, so the issue was using the batchmode on diagrams with a <help_text> element in it.

It will be fixed in the next release

**Closed** 2015-03-19 14:53 UTC
