### ISSUE TITLE
Umlet standalone gets confused with new current/active tab when closing a tab, also add close tab shortcut

### ISSUE THREAD

**Issue by garretwilson** [umlet/umlet#443] opened 2017-03-26 18:40 UTC
OMG, this is about to irritate the soup out of me.

I have created some simple class diagrams inside Eclipse. I open Umlet standalone, primarily because I don't want my computer hanging because of #310. I open two files, `foo.uxf` and `bar.uxf`. I use `File | Export as... | SVG...` to export `bar.uxf` to `bar.svg`. That works, and nothing freezes. Whew!

Then I click on the "X" to close `bar.uxf`. In addition to my lack of ability switch tabs, as reported in #442, apparently I can't close a tab using `Ctrl+F4` or `Ctrl+W`. Plus there isn't a `File | Close` menu option. Why can't Umlet follow the most basic of user interface conventions?

But here I'm finally getting to the core problem. After closing `bar.uxf`, the `foo.uxf` tab is selected. So I use `File | Export as... | SVG...` to export `foo.uxf` to `foo.svg` --- except that **the default filename in the dialog is `bar` and not `foo`**! Umlet apparently didn't notice that I had changed tabs, and is leaving the old default filename in the dialog.

This is extremely irritating, after I get out of Eclipse (because of #310) to export a bunch of files to SVG, then later to find out that they all have the wrong content because they were saved under the wrong filenames because the dialog default filename didn't follow the currently open tab.

Umlet is so cute and cool. Why, oh, why didn't you spend a little time to make it usable? Please, before adding new features, could you fix these huge usability bugs such as this one, #441 and #442?

I have sent over a monetary donation to help with further development.

**Comment by afdia** [comment] 2017-03-26 20:31
Hi

The File > Close menu entry and a Ctrl+W shortcut sound reasonable.
The second thing you mentioned is a bug. It seems that UMLet doesn't "activate" the newly visible diagram correctly after closing another one.

Thanks for the report

**Comment by afdia** [comment] 2017-03-26 20:56
the problems should be fixed in the next version (these bugs are simple to fix compared to the Eclipse problems which may be caused by the complex interaction with the eclipse plugin system)

I have also renamed the issue to reflect the reported bug and change

**Closed by afdia** 2017-03-26 20:56 UTC
Labels: bug
