### ISSUE TITLE
umlet hangs forever when dragging dot to arrow in lt=<<. 

### ISSUE THREAD

**Issue by marhkb** [umlet/umlet#349] opened 2016-01-15 12:13 UTC
The title may sound a little weird, but I do not know how to explain the issue exactly.
Here is a short screen record I made showing the issue:

[desktop_video-2.mp4.zip](https://github.com/umlet/umlet/files/91806/desktop_video-2.mp4.zip)

In my own words:
When i try to altering a ------I> (I think it is a generalization) and want to give it a crease a dot appears what is still normal. But when I drag this dot onto the end arrow of the generalization the application hangs.

System: Arch Linux x86_64 
Kernel: 4.3.3-2-ck
DE: KDE
JRE: jre8-openjdk-infinality 8.u60-1
Umlet ver: 14.1

**Comment by afdia** [comment] 2016-01-15 12:34
Thanks for the report

Unfortunately I cannot reproduce it on Windows7
Does it work in v13.3?

**Comment by marhkb** [comment] 2016-01-15 12:45
No problem. :)

I have just downgraded to 13.3 and i can confirm the issue is NOT present here. 
To be sure I adjusted preferences as I had them in 14.1 (inclusive L&F set to gtk+).

**Comment by afdia** [comment] 2016-01-15 13:09
One more question:
Does UMLet always hang if you drag the ends together or only sometimes?

I just want to make sure the issue is reproducible and the relation ends are the source of the problem.

**Comment by marhkb** [comment] 2016-01-15 13:33
Yes always, when I drag a middle dot onto the arrow end. 
Be aware:
This issue only occurs when i drag a dot out of the middle to the end dot. So a) works without issues. When I try b) umlet hangs with high cpu usage.

a)
(<)------------------()
  |____________|
Dragging the right dot onto the left dot works

b)
(<)--------()----------()
  |______|
Dragging a dot between the start and end dot onto the end dot lets umlet hang

This issue is only present in the following associations:
1) lt=<<.
2) lt=<.

All other associations work as far as I can see.
_____

**Comment by afdia** [comment] 2016-01-15 16:29
Unfortunately I still cannot reproduce the issue.
It's interesting that it seems to be linked to the lt, because the lt is only a minor detail about what is drawn, but the dragging and merging of points should work the same for all relations.

Perhaps you can try the following to make sure the issue is linked to the linetype (which seems unlikely according to how the UMLet code works):
1. add the `lt=<<-` relation from the class palette and try to provoke a freeze (should not be possible as you said)
2. change the lt to `lt=<<..` and try again (perhaps the dotted line is also problematic?)
3. change to `lt=<<.` and try again (now the freeze should occur)

Other suggestions to find the source of the issue would be:
1. I've seen in the video that you use `-Dsun.java2d.xrender=f` as parameter. perhaps try it without the parameter to see if the issue remains
2. Perhaps try starting UMLet with Java7
3. Try to remove the current umlet.cfg and restart with default settings

It is also possible to enable verbose logging information by referencing a log4j.properties file at startup (e.g. you can use [log4j.zip](https://github.com/umlet/umlet/files/92165/log4j.zip) which should log relevant information into a log4j.log file in the current directory)
The start command would be: `-Dlog4j.configuration=file:log4j.properties -jar umlet.jar` (log4j.properties location must be set correctly)

Perhaps the logging provides further information about the freeze (it could also grow very large if an infinite loop is causing the freeze)

**Comment by marhkb** [comment] 2016-01-15 19:03
I already grabbed the sources this afternoon and debugged it. I think the issue is in sun.java2d.pisces.Dasher#lineTo(float, float). Here, in a while(true) loop, the break statement is never reached. Both doubles are NaN. So the awt-event-queue is hanging.
If you cannot reproduce this I first try to use a different JRE (openjdk-7 and sun-jre) and see if the issue is still present.

If that does not help I will post the logs.

PS: Yes, it seems all dotted lines are concerned

**Comment by marhkb** [comment] 2016-01-15 20:21
I compiled and ran umlet with different JDKs and JREs.
The issue is gone when run umlet with the oracle JRE.
So this is related to openjdk. I am going to report this to their bug tracker in the next days.

**Comment by afdia** [comment] 2016-01-16 08:26
ok thanks for the analysis.
after reporting please post the link to the issue (to help other people which are using openjdk) and close this one.

**Closed** 2023-05-18 20:53 UTC
Labels: relation, jdk issue
