### ISSUE TITLE
Umlet freezes when dragging the arrow-end of a dashed relation into a middle-point of the relation

### ISSUE THREAD

**Issue by tuppi-ovh** [umlet/umlet#660] opened 2021-08-23 13:41 UTC
UMLet 14.3.0 on Windows 10, standalone.

I have this kind of diagram:

![image](https://user-images.githubusercontent.com/59368736/130456628-51cfc0dd-9276-42af-afb1-b2fd4866942f.png)

When I try to move a gray block a little bit higher by selecting everithing by "CTRL + mouse" and moving the selection higher:

![image](https://user-images.githubusercontent.com/59368736/130457075-5acbff3f-db3d-404d-96cb-70794eddad95.png)

It freezes completely the interface and I need to kill the application:

![image](https://user-images.githubusercontent.com/59368736/130457160-099523d6-af98-414b-ae8a-d3e73dd3922e.png)

The issue can be related to layers as I play with "layer" value (from 0 to 3). I join also a [source file](https://github.com/umlet/umlet/files/7032363/issue.zip) of this diagram.

**Comment by afdia** [comment] 2021-08-23 14:06
Hi

I tried to reproduce the issue in your attached uxf but I cannot, but the box is not gray in your example diagram so maybe the issue is not there?

Lets try to track the issue down:
- At first try to reproduce the issue with the attacked uxf file if possible (just to make sure its present)
- Do you move the elements by moving the mouse or by tapping the up arrow on your keyboard? Maybe try both ways and see if one of them work
- Maybe start Umlet by opening a cmd (command prompt), going into the Umlet dir, and typing "java -jar umlet.jar". You should see an Exception/Error text in the command prompt if Umlet crashes
- Also please let us know which Java version you are using

You can also try to zoom one step out and one step in in. Zooming can fix some minor pixel misalignments (they should not happen, but maybe a bug or manual editing of the uxf file can cause such bugs)

**Comment by tuppi-ovh** [comment] 2021-08-23 14:46
Sorry, due to a crash, the file wasn't saved. The correct one: 
[issue.zip](https://github.com/umlet/umlet/files/7032714/issue.zip). But it reproduces also with a firstly joined file.

the log of `java -jar umlet.jar` execution:
```
log4j:WARN No appenders could be found for logger (com.baselet.control.enums.Program).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
``` 
It is import to precise that it is not a crash by error or exception, it is just a freeze with 100% CPU load.

I move items by mouse,  but it freezes also by "arrow up".

Java version:
```
openjdk version "1.8.0_222-2-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_222-2-ojdkbuild-b10)
OpenJDK Server VM (build 25.222-b10, mixed mode)
```

**Comment by afdia** [comment] 2021-08-23 15:17
Ok thanks, I can reproduce the issue using AdoptOpenJDK8 on Win10
Unfortunately this issue is known #523 and #349

As far as I know it is an issue with the JDK8. According to my previous comments it was not present in past JDK8 versions on Windows but maybe some patch unified the JDK8 codebase and now it is also there in Win10

It happens within a draw-method call so I cannot really get any more information about it.

I guess your options are:
- use JDK11 where the issue is not present (other JDKs after 8 will probably work too)
- avoid dashed arrows (the issue only occurs there)
- use the vscode Plugin or the web based https://umletino.com which both avoid a JDK and therefore this issue (this version will probably get a quite large update soon as it uses the same codebase as our newly created vscode plugin)

I will mark the issue as a duplicate but leave it open for some time to see if there are more reports now that it seems to appear in Windows JDK8 too

Btw this is a reduced diagram which is still enough to reproduce the issue (just drag the box straight up with the mouse):
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<diagram program="umlet" version="14.3.0">
  <zoom_level>11</zoom_level>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>275</x>
      <y>396</y>
      <w>242</w>
      <h>99</h>
    </coordinates>
    <panel_attributes/>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>319</x>
      <y>352</y>
      <w>66</w>
      <h>66</h>
    </coordinates>
    <panel_attributes>lt=&lt;.</panel_attributes>
    <additional_attributes>40.0;40.0;40.0;10.0;10.0;10.0</additional_attributes>
  </element>
</diagram>
```

**Comment by tuppi-ovh** [comment] 2021-08-24 07:10
@afdia Thank you for your response!

**Comment by afdia** [comment] 2023-10-11 18:11
If it happens again with Java11+ please reopen, otherwise I will close it as we cannot do anything about it and Java8 is quite old

**Closed by afdia** 2023-10-11 18:11 UTC
Labels: duplicate, bug, relation, jdk issue
